### PR TITLE
added basic makefile

### PR DESCRIPTION
**Pull request by kafkasl**
Added Makefile for convenience

# Definition of DONE
Your changes will be ready for merging after each of the steps below have been completed:

### Testing
- [ ] Unit tests written
- [ ] Tested locally with Inframock
- [ ] Deployed to staging

To set up easy local testing with inframock, follow the instructions here: https://github.com/biomage-ltd/inframock
To deploy to the staging environment, follow the instructions here: https://github.com/biomage-ltd/biomage-utils

### Documentation updates
Is all relevant documentation updated to reflect the proposed changes in this PR?

- [x] Relevant Github READMEs updated
- [x] Relevant wiki pages created/updated

### Approvers
- [ ] Approved by a member of the core engineering team
- [ ] (UX changes) Approved by vickymorrison (this is her username, tag her if you need approval)

### Just before merging:
- [ ] After the PR is approved, the `unstage` script in here: https://github.com/biomage-ltd/biomage-utils is executed. This script cleans up your deployment to staging

### Optional
- [X] Photo of a cute animal attached to this PR

image

### CODE REVIEW

**Review by xverges — APPROVED** [review]
Approving. Since no responses appeared in the slack thread, make your own call regarding `ci` vs `install` https://docs.npmjs.com/cli/v7/commands/npm-ci

**Comment by kafkasl** [comment]
> Approving. Since no responses appeared in the slack thread, make your own call regarding `ci` vs `install` https://docs.npmjs.com/cli/v7/commands/npm-ci

after reading your link and this one https://stackoverflow.com/a/53325242/2221409 I believe using `npm install` is a better option. `ci` will remove & reinstall all modules every time even for a single new dependency, and the ability of `install` to add missing dependencies means that other team will be able to keep working if something is missing instead of having a failing build. We should use `ci` for continuous integration in the PR & tests and that should be enough.

**Comment by xverges** [comment]
Just to clarify: the docs statement that _individual dependencies cannot be added with this command_  means that `npm install` can do two different things:
* `npm install` makes sure that everything in `package.json/package-lock.json` is installed.
* `npm install packageName` installs a single package and updates `package.json/package-lock.json` (that's the bit about _individual dependencies_).

If something is missing from `package.json`, none of the two commands puts us in a better position.

A possible side effect of `npm install` is that `package-lock.json` can be updated.

**Comment by kafkasl** [comment]
Oh I see, I didn't get the bit about npm installing a single dep. I will merge it how it is for consistency with the rest of packages for now. But probably it will make sense to switch all of them to `npm ci` when/if we use the `make install` during the new CI stages & deployment stages

**Pull request merged**
